// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArmDrop.h"
#include "Commands/ArmLift.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Fire.h"
#include "Commands/RollerBackwards.h"
#include "Commands/RollerForward.h"
#include "Commands/RollerLift.h"
#include "Commands/RollerStop.h"
#include "Commands/SwitchShift.h"
#include "Commands/TankDrive.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joyPad = new Joystick(3);
	
	armBtn2 = new JoystickButton(joyPad, 5);
	armBtn2->WhenPressed(new ArmDrop());
	armBtn1 = new JoystickButton(joyPad, 4);
	armBtn1->WhenPressed(new ArmLift());
	rollerBtn3 = new JoystickButton(joyPad, 3);
	rollerBtn3->WhenPressed(new RollerBackwards());
	rollerBtn2 = new JoystickButton(joyPad, 2);
	rollerBtn2->WhenPressed(new RollerForward());
	rollerBtn1 = new JoystickButton(joyPad, 1);
	rollerBtn1->WhenPressed(new RollerStop());
	joy2 = new Joystick(2);
	
	joy2Trigger = new JoystickButton(joy2, 1);
	joy2Trigger->WhenPressed(new SwitchShift());
	joy1 = new Joystick(1);
	
	joy1Trigger = new JoystickButton(joy1, 1);
	joy1Trigger->WhenPressed(new Fire());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("TankDrive", new TankDrive());

	SmartDashboard::PutData("Fire", new Fire());

	SmartDashboard::PutData("RollerForward", new RollerForward());

	SmartDashboard::PutData("RollerBackwards", new RollerBackwards());

	SmartDashboard::PutData("RollerStop", new RollerStop());

	SmartDashboard::PutData("RollerLift", new RollerLift());

	SmartDashboard::PutData("ArmLift", new ArmLift());

	SmartDashboard::PutData("ArmDrop", new ArmDrop());

	SmartDashboard::PutData("SwitchShift", new SwitchShift());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getjoyPad() {
	return joyPad;
}

Joystick* OI::getjoy2() {
	return joy2;
}

Joystick* OI::getjoy1() {
	return joy1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

JoystickButton* OI::getjoy1Trigger() {
	return joy1Trigger;
}
