// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "AutonomousCommand.h"
#include "../RobotMap.h"
#include "Fire.h"
#include "../Constants.h"

Timer t;

AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	string val = "hot";
	int setHot=0;
	t.Start(); //starts timer
	t.Reset(); //resets timer to zero
	Robot::arm->roll1->Set(Relay::kReverse);
	//RobotMap::armSol1->Set(false); //turns off sol to lower arm
	//RobotMap::armSol2->Set(true);
	RobotMap::driveenLeft->Reset(); //resets left encoder
	RobotMap::driveenRight->Reset(); //resets right encoder
	Robot::drive->LeftDrive->Set(FORWARDSPEED*-.87); //turns right
	Robot::drive->RightDrive->Set(FORWARDSPEED*1); //turns right faster
	
//	double d=-2*(1-((Robot::claw->pot1->GetValue()-POTBOTTOM)/(FIRINGPOINT-POTBOTTOM)));
	while(RobotMap::driveenLeft->Get() > (ENCODERDISTANCE+100)*-1 || RobotMap::driveenRight->Get() > ENCODERDISTANCE*-1) 
	{
		if(RobotMap::driveenLeft->Get() < (ENCODERDISTANCE+100)*-1)
		{
			Robot::drive->LeftDrive->Set(STOPSPEED);
		}
		if(RobotMap::driveenRight->Get() < ENCODERDISTANCE*-1)
		{
			Robot::drive->RightDrive->Set(STOPSPEED);
		}
		if(!Robot::claw->ballinSwitch->Get() && Robot::arm->roll1->Get()==Relay::kReverse)
		{
			Robot::arm->roll1->Set(Relay::kOff);
		}
		printf("autodrive\n");
		t.Reset();
		if(t.Get()<1.1f)
		{
			Robot::Hot = Robot::table->GetString(val);
		}
//		if(RobotMap::driveenLeft->Get() <= ENCODERDISTANCE*-1)
//		{
//			Robot::drive->LeftDrive->Set(STOPSPEED);
//		}
//		if(RobotMap::driveenRight->Get() <= ENCODERDISTANCE*-1)
//		{
//			Robot::drive->RightDrive->Set(STOPSPEED);
//		}
		//printf("Left:%d		Right:%d\n",RobotMap::driveenLeft->Get(),RobotMap::driveenRight->Get());
//		while(Robot::claw->pot1->GetValue()!=FIRINGPOINT && !Robot::oi->getjoythumb1()->Get())
//		{
//			d=-2*(1-((Robot::claw->pot1->GetValue()-POTBOTTOM)/(FIRINGPOINT-POTBOTTOM)));
//			Robot::claw->lifter->Set(d);
//			if(d<0.05f && d>-0.05f)
//			{
//				d=0;
//			}
//		}
	} //if the robot has turned enough
	if(Robot::Hot=="True")
	{
		setHot=1;
	}
	if(Robot::Hot=="False")
	{
		setHot=0;
	}
	RobotMap::clawarmSol->Set(true);
	Robot::arm->roll1->Set(Relay::kOff);
	Robot::drive->LeftDrive->Set(STOPSPEED); //stop turning
	Robot::drive->RightDrive->Set(STOPSPEED); //stop turning
	//double i=-2*(1-((Robot::claw->pot1->GetValue()-POTBOTTOM)/(FIRINGPOINT-POTBOTTOM)));
	Robot::claw->lifter->Set(DOWNSPEED);
	while(Robot::claw->pot1->GetValue()<430)
	{
		printf("%d\n",setHot);
	}
	Robot::claw->lifter->Set(STOPSPEED);
	//RobotMap::armSol1->Set(true);
	//RobotMap::armSol2->Set(false);
	
	while(Robot::claw->pot1->GetValue()!=FIRINGPOINT && !Robot::oi->getjoythumb1()->Get())
	{
		if(!Robot::claw->ballinSwitch->Get() && Robot::arm->roll1->Get()==Relay::kReverse)
		{
			Robot::arm->roll1->Set(Relay::kOff);
		}
		//i=-2*(1-((Robot::claw->pot1->GetValue()-POTBOTTOM)/(FIRINGPOINT-POTBOTTOM)));
		Robot::claw->lifter->Set(-5*(1-((Robot::claw->pot1->GetValue()-POTBOTTOM)/(400-POTBOTTOM))));
		//printf("%d\n",Robot::claw->pot1->GetValue());
		printf("%d\n",setHot);
	}
//	RobotMap::armSol1->Set(true);
//	RobotMap::armSol2->Set(false);
	Robot::claw->lifter->Set(STOPSPEED);
	Robot::drive->LeftDrive->Set(0); //stop turning
	Robot::drive->RightDrive->Set(0);
	while(setHot==0 && t.Get()<HALFAUTO) { //wait for hot to be true or until five seconds pass
		//Wait(0.1f);
		Robot::drive->LeftDrive->Set(0); //stop turning
		Robot::drive->RightDrive->Set(0);
	}
	
	t.Reset();
	while(t.Get()<0.5f)
	{
		Robot::drive->LeftDrive->Set(0); //stop turning
		Robot::drive->RightDrive->Set(0);
	}
	RobotMap::clawfourshotSol1->Set(true);
	RobotMap::clawfourshotSol2->Set(true);
	Robot::claw->fire(); //execute fire command
	Robot::drive->LeftDrive->Set(0); //stop turning
	Robot::drive->RightDrive->Set(0);
	
	End();
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	
}


// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	Robot::drive->LeftDrive->Set(0); //stop turning
	Robot::drive->RightDrive->Set(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {
	Robot::drive->LeftDrive->Set(0); //stop turning
	Robot::drive->RightDrive->Set(0);
}

