// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "ClawUp.h"

bool high = false;

ClawUp::ClawUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ClawUp::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void ClawUp::Execute() {
	if(!high) { //if claw is not too high
		RobotMap::clawlifter->Set(.2); //move up
	}
	else { //if it is
		RobotMap::clawlifter->Set(0); //stop
	}
	if(Robot::claw->pot1->GetValue() >= 20) { //if claw is at top
		high = true; //claw is too high
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ClawUp::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void ClawUp::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClawUp::Interrupted() {

}
