// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "SwitchShift.h"
#include "../Subsystems/Drive.h"
#include "../RobotMap.h"

SwitchShift::SwitchShift() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void SwitchShift::Initialize() {
	printf("Gear changed\n"); //show that gear has changed (debugging)
}

// Called repeatedly when this Command is scheduled to run
void SwitchShift::Execute() {
	RobotMap::driveswitchSol1->Set(true); //activate the solenoid (switch gears)
	RobotMap::driveswitchSol2->Set(false);
}

// Make this return true when this Command no longer needs to run execute()
bool SwitchShift::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void SwitchShift::End() { //contents should not be needed (added as fail-safe)
	RobotMap::driveswitchSol1->Set(false);
	RobotMap::driveswitchSol2->Set(true);
	printf("Gear reset\n");
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SwitchShift::Interrupted() {
	RobotMap::driveswitchSol1->Set(false); //deactive the solenoid (change gears back)
	RobotMap::driveswitchSol2->Set(true);
	printf("Gear reset\n"); //show that the gear has been reset
}
