// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "Claw.h"
#include "../Robotmap.h"
#include "../Robot.h"
#include "../Constants.h"

Timer z;

Claw::Claw() : Subsystem("Claw") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	triggerSol1 = RobotMap::clawtriggerSol1;
	triggerSol2 = RobotMap::clawtriggerSol2;
	ballSwitch = RobotMap::clawballSwitch;
	ballinSwitch = RobotMap::clawballinSwitch;
	shooterSol1 = RobotMap::clawshooterSol1;
	shooterSol2 = RobotMap::clawshooterSol2;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	pot1 = RobotMap::clawPot1;
	lifter = RobotMap::clawLifter;
	z.Start();
	z.Reset();
}
    
void Claw::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Claw::fire()
{
	Robot::claw->lifter->Set(STOPSPEED);
	z.Reset();
	RobotMap::clawtwoshotSol1->Set(false);
	RobotMap::clawtwoshotSol2->Set(false);
	//RobotMap::clawfourshotSol1->Set(false);
	//RobotMap::clawfourshotSol2->Set(false);
//	Robot::claw->shooterSol1->Set(true);
//	Robot::claw->shooterSol2->Set(false);
//	RobotMap::armSol1->Set(true);
//	RobotMap::armSol2->Set(false); //Lifts the Arm up
//	printf("armup");
//	while(z.Get()<ARMTOTRIGGER)
//	{
//		Robot::drive->M_Drive(Robot::oi->getjoy1(), Robot::oi->getjoy2());
//	}
	RobotMap::clawtriggerSol->Set(true);		//Pull in Trigger
	printf("triggerdown");
	while(z.Get()<TRIGGERTORESET)
	{
		Robot::drive->M_Drive(Robot::oi->getjoy1(), Robot::oi->getjoy2());
	}
	printf("outloop1");
	//RobotMap::clawarmSol->Set(false);
	/*RobotMap::armSol1->Set(false);
	RobotMap::armSol2->Set(true);*/
	RobotMap::clawtwoshotSol1->Set(true);
	RobotMap::clawtwoshotSol2->Set(true);
	RobotMap::clawfourshotSol1->Set(true);
	RobotMap::clawfourshotSol2->Set(true);
	z.Reset();
	printf("inloop2");
	while(Robot::claw->ballSwitch->Get() && !Robot::oi->getjoythumb1()->Get())// && z.Get()<TRIGGERDELAY)
	{
		Robot::drive->M_Drive(Robot::oi->getjoy1(), Robot::oi->getjoy2());
	}
	printf("\noutloop2\n");
	RobotMap::clawtriggerSol->Set(false);
	z.Reset();
	while(z.Get()<0.1f)
	{
		Robot::drive->M_Drive(Robot::oi->getjoy1(), Robot::oi->getjoy2());
	}
	RobotMap::clawtwoshotSol1->Set(false);
	RobotMap::clawtwoshotSol2->Set(false);
	RobotMap::clawfourshotSol1->Set(false);
	RobotMap::clawfourshotSol2->Set(false);
	
}



