// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "Claw.h"
#include "../Robotmap.h"
#include "../Robot.h"

Claw::Claw() : Subsystem("Claw") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	triggerSol1 = RobotMap::clawtriggerSol1;
	triggerSol2 = RobotMap::clawtriggerSol2;
	ballSwitch = RobotMap::clawballSwitch;
	shooterSol1 = RobotMap::clawshooterSol1;
	shooterSol2 = RobotMap::clawshooterSol2;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Claw::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Claw::fire()
{
	//todo LIFT INTAKE ARM HERE
	Robot::claw->triggerSol1->Set(Relay::kOn);		//Pull in Trigger
	Robot::claw->triggerSol2->Set(Relay::kOff);		//Pull in Trigger
	Robot::claw->shooterSol1->Set(Relay::kOff);		//No Pressure to Shooter Solenoids
	while(!Robot::claw->ballSwitch->Get() || !Robot::oi->getjoy1Trigger())
	{
		//Waiting until microswitch is hit
		//or until loop is exited by pressing button
		//todo Make new button function instead of joy1Trigger-will call command again
	}
	Robot::claw->triggerSol1->Set(Relay::kOff);		//Push out Trigger
	Robot::claw->triggerSol2->Set(Relay::kOn);		//Push out Trigger
	Robot::claw->shooterSol1->Set(Relay::kOn);		//Pressurize Shooter Solenoids
	
}



